### ISSUE TITLE
Can I translate this repo to chinese?

### ISSUE THREAD

**Issue by Leezj9671** [WebBreacher/offensiveinterview#18]
This is an exciting Repo! Can I translate it to chinese? If your answer is yes, I want to know if authorization/license is required.
Thx.

**Comment by WebBreacher** [comment]
very happy you like the project. 

the license can be found https://github.com/WebBreacher/offensiveinterview/blob/master/LICENSE.md.

instead of making your own, maybe you could translate the content and submit it to this project so all the versions would be in a single repository?

**Comment by Leezj9671** [comment]
Hi, I got some trouble while traslating `open.md`, in  `Tech Questions` - `General Pentest`，I don't really understand what quesion 16 `manage client data` means? And `engagement` means the process of pentest?

**Comment by WebBreacher** [comment]
Ah. no problem. "When you are doing a security assessment or penetration test, you have a lot of output from your tools (nmap, vulnerability scanner, other tools) plus you have notes...what do you do to organize all of those so that you can stay working well and not forget things?"

**Comment by Leezj9671** [comment]
Okay, I've already translated it all.🎉
The questions is comprehensive. Traslated version is on the `translate-zhcn` branch.
[Leezj9671/offensiveinterview](github.com/Leezj9671/offensiveinterview)
