### ISSUE TITLE
blog/contributions

### ISSUE THREAD

**Issue by digininja** [WebBreacher/offensiveinterview#2]
Where is your blog?
What projects do you contribute to?
What conferences do you attend?
What conferences have you spoken at?
Name a couple of people in the industry that you'd look to for advice/trust their advice. - Asking this to make sure they are active and know who does what, if they are claiming to be wifi experts and don't name people like Josh Wright then they are lying.

**Comment by WebBreacher** [comment]
Close by pull #3 . Thanks @digininja
